"""
================================================================================
SLM Visualization and Logging (visualize.py)
================================================================================

[Sequence: 5 of 6]

What this file is about:
This script allows you to actually see how well your AI is learning. 
During training, `train.py` saves the loss and accuracy to a file called 
`training_logs.json`. This script reads those logs and draws professional 
line graphs using Matplotlib.

How this code works step by step:
1. It looks for the JSON log file generated by your training loop.
2. It extracts the raw numbers:
   - Training Loss (how wrong the model is on data it HAS seen)
   - Validation Loss (how wrong the model is on data it HAS NEVER seen)
   - Validation Accuracy (what % of time did it guess the exact right next word?)
3. It uses `matplotlib.pyplot` to draw two side-by-side graphs.
4. It saves a `.png` copy of the graphs directly into the `logs/` folder so you can
   keep a historical record of your training progress.
5. It displays these graphs in a pop-up window so you can visually confirm.
"""

import json
import os
import matplotlib.pyplot as plt

def plot_metrics():
    log_file = "logs/training_logs.json"
    chart_output_path = "logs/training_graphs.png"
    
    # 1. Check if training has generated logs yet
    if not os.path.exists(log_file):
        print(f"Error: Could not find {log_file}.")
        print("You need to run `python train.py` and wait for the first evaluation step (eval_iters) before plotting graphs.")
        return

    # 2. Extract Data
    with open(log_file, "r") as f:
        logs = json.load(f)

    steps = logs["steps"]
    train_loss = logs["train_loss"]
    val_loss = logs["val_loss"]
    val_acc = logs["val_acc"]
    
    if not steps:
        print("Log file is currently empty. Wait for training to progress.")
        return

    # 3. Setup the Matplotlib Figure
    # We create a wide figure with 2 subplots (1 row, 2 columns)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    
    # --- SUBPLOT 1: Loss ---
    ax1.plot(steps, train_loss, 'g-', label='Train Loss (Lower is better)', linewidth=2)
    ax1.plot(steps, val_loss, 'r-', label='Validation Loss', linewidth=2)
    ax1.set_title("SLM Training Error Over Time")
    ax1.set_xlabel("Training Steps")
    ax1.set_ylabel("Cross Entropy Loss")
    ax1.legend()
    ax1.grid(True, linestyle='--', alpha=0.6)
    
    # --- SUBPLOT 2: Accuracy ---
    # We multiply by 100 to show percentages instead of decimals (e.g. 0.45 -> 45%)
    val_acc_percent = [acc * 100 for acc in val_acc]
    ax2.plot(steps, val_acc_percent, 'b-', label='Validation Accuracy (Higher is better)', linewidth=2)
    ax2.set_title("SLM Next-Token Accuracy Over Time")
    ax2.set_xlabel("Training Steps")
    ax2.set_ylabel("Accuracy (%)")
    ax2.legend()
    ax2.grid(True, linestyle='--', alpha=0.6)
    
    # Optional: Fill the area under the accuracy curve to make it look professional
    ax2.fill_between(steps, 0, val_acc_percent, alpha=0.1, color='blue')

    # Final Polish
    plt.tight_layout()
    
    # Auto-save the graph so you can review it later!
    plt.savefig(chart_output_path, dpi=300)
    print(f"Graph generated and automatically saved to: {chart_output_path}")
    print("Close the image window to end the script.")
    plt.show()

if __name__ == "__main__":
    print("Reading training logs and generating graphs...")
    plot_metrics()
